set runtimepath+=~/.config/vim,~/.config/vim/after
execute pathogen#infect()

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.config/vim/plugged')

" Best color scheme
Plug 'morhetz/gruvbox'

" vim-go
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries'}

" rust.vim
Plug 'rust-lang/rust.vim'

" Elixir
Plug 'elixir-editors/vim-elixir'

" Tmux navigator
Plug 'christoomey/vim-tmux-navigator'

" Initialize plugin system
call plug#end()

" viminfo
set viminfo+=n~/.config/vim/viminfo

let g:rustfmt_autosave = 1

syntax enable
filetype plugin indent on

" Indentation Options
set autoindent
set expandtab
set shiftwidth=2
set tabstop=2

" Search
set hlsearch
set ignorecase
set incsearch
set smartcase

" UI
set ruler
set termguicolors
set background=dark
colorscheme gruvbox
set cursorline
set number
set relativenumber
set noerrorbells
set title

" Misc
set history=100

" Directory explorer settings
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 3
let g:netrw_altv = 1
let g:netrw_winsize = 25
augroup ProjectDrawer
  autocmd!
augroup END
cnoreabbrev vex Vex
